### ISSUE TITLE
Comments that are replies to comments are not counted to the annotated comment_count

### ISSUE THREAD

**Issue by kleingeist** [liqd/adhocracy4#117]
When using `models.query.CommentableQuerySet.annotate_comment_count` only direct comments on the item are counted, not the replies to comments.
I would expect the `comment_count` to include the sum of all comments, including the replies.
What is the intended behavior?

**Comment by MagdaN** [comment]
I think, we had this discussion and somehow decided to just show this count. I think it was because we thought, that a comment on a comment might change the subject, so you cant be sure if those comments are really of value. Also it might be confusing if you have let's say 10 comment and underneath the last comment you have 30 subcomments - then the count would say 40, but you see only 10.

**Comment by kleingeist** [comment]
thanks for the clarification. we will keep it the same for now in meinBelrin
