### ISSUE TITLE
Documentation and Instructions

### ISSUE THREAD

**Issue by dude8604** [liqd/adhocracy4#300]
I'm having trouble figuring out how to install and run Adhocracy. I'm a programmer and have set up similar things before, and I still couldn't figure out what to do. So the README should have instructions on basic setup and use of Adhocracy. I think it would help a lot of users. In the meantime, could someone tell me how to set it up? Thanks.

**Comment by fuzzylogic2000** [comment]
Yes! You're right and made this issue we have in our head (for a while) a real one. Thanks!
We use adhocracy more like a library and use or exchange what we need in different projects. To start, you can use meinBerlin (https://github.com/liqd/a4-meinberlin) and change stuff according to your needs from there. Or you use the cookie-cutter (https://github.com/liqd/a4-cookiecutter), which lets you start with a blank project, but has dependencies that are pretty outdated. 
Please let us know how well you get along with these and what the problems are!

**Comment by dude8604** [comment]
Is it possible to customize it enough from within the software or will it take a lot of programming? I'm trying to start a crowdsourced novel about liquid democracy that is written by a liquid democratic process. Is that something I can do with adhocracy?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by fuzzylogic2000** [comment]
Hmm. Adhocracy4 is focusing more on participation that lets you comment on topics, ideas or documents or debate about a certain topic. For that we have projects, modules and phases then determining the rules to what is allowed by whom and when. While it would theretically be possible to add some module where people could work on a document for a certain time and then rate or comment paragraphs later, it would take a lot of programming to get the part where people can work together on a document.

**Comment by Chealer** [comment]
Thanks @dude8604 , there is indeed much lacking in that area. To be clear, you are considering to write a **fiction** book, right? And are you [that Philip Weiss](https://en.wikipedia.org/wiki/Philip_Weiss)?

Here are a couple other things I would expect documentation to cover:
1. The names used to refer to this version of Adhocracy (which apparently include "adhocracy4", "Adhocracy4" and "A4")
1. If this product "implements" liquid democracy", I would expect that to be clearly and prominently indicated in the README. I am looking at a big pile of immature code which I hope represents the future of democracy, but I have no idea how to test it, nor if it even has anything to do with liquid democracy.

**Comment by dude8604** [comment]
No, I'm not that Philip Weiss. The idea was to write a fiction book, but I'm not sure if I'm actually going to do it. I don't know if Adhocracy is the right platform for what I want to do, but I haven't found anything better either.

**Comment by Chealer** [comment]
@dude8604 , is this to say you managed to use Adhocracy, or that you haven't found any potential tool at all?
By the way, I have never written published fiction, and never planned to do so, but I find your idea intriguing... although I reckon it would most likely be a technological challenge. If your project gets serious and you get serious means,  I may also be willing to help for a "friendly fee" if such software development is needed.

Another top documentation priority would be discussion forums.

**Comment by rmader** [comment]
@dude8604 @Chealer: if you are speaking about liquid democracy in the sense of delegated voting mechanism I'm sorry to have to inform you that we do not aim to implement that any more. I'd suggest to try liquid feedback instead: https://liquidfeedback.org/

To elaborate on this: our understanding of liquid democracy has more and more evolved in the direction of discourses, focussing e.g. on discussion rather than on voting mechanisms. 

As for documentations etc.: that's indeed an area were we need to improve, therefore leaving this issue open until that's that's done :)

**Comment by Chealer** [comment]
Thanks @rmader 

In that case, can someone here either un-archive the liqd/adhocracy project so that its issues can be discussed again, or at a minimum amend the README file with regards to the relation with this project? The current situation is very misleading:
1. The older Adhocracy project implements liquid democracy concepts and says adhocracy is now developed in this project, without any indication of the change in goal/purpose.
2. This project is develop by the Liquid Democracy organization and lacks the slightest indication that it does not aim to implement liquid democracy.

**Comment by sabinammm** [comment]
@fuzzylogic2000 should this issue remain open to continually update the readme in the projects or can we close this?

**Comment by fuzzylogic2000** [comment]
@sabinammm As we added detailed installation instructions to a+, I think, we can close this as soon as we added a link to that and/or explanation to the a4 docs. And we have that in here: https://github.com/liqd/adhocracy4/blob/main/docs/development.md
