### ISSUE TITLE
API permissions do not consider phases

### ISSUE THREAD

**Issue by 2e2a** [liqd/adhocracy4#31]
When posting a comment or rate, `object_pk` and `content_type_id`can be set to any project item. The phase permission of the project are not being checked.

**Comment by slomo** [comment]
### problem statement

- currently two permission systems in use (drf permissions & django-rules)
- django-rules has good integration with a4 model
   - checks phases if participant creates new resource
   - checks phase if participant updates own resource
   - prevents information leakage and modification of content in private projects
   - enables all operations for admins, initiator and moderators
- drf permissions has not so good integration
   - enables moderator to update all resources in own project
   - checks that user can only modify own resource
   - does **not** prevent information leakage or modification of content in private projects
     - but there are no APIs to get content from any project (so leakage isn't an issue)
     - modification is (eg. I can comment/rate in any private project if I know a ressource id)
   - does **not** check phases for participant operations

### solution

> combine drf permissions and django-rules

- django-rules needs to know to which module/project a resource belongs
   - because project might be private or in wrong phase
- easy for modifying existing content (get content_object of comment/rate etc)
- hard for creating content
   - only encoded in body, which is parsed after permission checks
- hard for listing content
   - only encoded in optional filter parameters

⇒ **subproblem**: we need to know context 
  - always add module to all api requests (as path part or non-optional parameter)
  - allow each API endpoint to specify its own context (eg `object_pk` and `content_type` for comments/rates)
